apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderpubsub  # This should match the pubsub name in your app (e.g., 'orderpubsub')
  namespace: default  # Replace with your namespace (or leave blank for default)
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://sb-fdrtujfacex4o.servicebus.windows.net/;SharedAccessKeyName=AzureDaprAuthRule;SharedAccessKey=VVMljASrA+7FY+rQmgXaKmKQYyOHNWfkc+ASbKAfp1A=;EntityPath=orders"
   
